#! /bin/bash
cd PX4-Autopilot || return
make clean &&
make px4_sitl gazebo DONT_RUN=1
cp -rf ../copy-folder/launch .
cp -rf ../copy-folder/models ./Tools/sitl_gazebo
cp -rf ../copy-folder/worlds ./Tools/sitl_gazebo
